'use client'

import { useState } from 'react'
import { isCvForgeGenerated } from '@/lib/parser/cvForgeDetection'
import { WorkbenchSectionCard } from '@/components/shared/workbench/WorkbenchSectionCard'
import { type ParserDocument } from '../upload/parserTypes'

export function ExtractionDiagnostics({ document }: { document: ParserDocument | null }) {
  const [isExpanded, setIsExpanded] = useState(true)
  if (!document) return <EmptyDiagnostics />

  const extraction = document.extraction
  const isForge = extraction ? isCvForgeGenerated(extraction.metadata) : false
  const reliability = isForge ? 100 : document.heuristic?.confidence ?? 0
  const hasSelectableText = Boolean(extraction?.text.trim())

  return (
    <WorkbenchSectionCard
      title="Extraction Analysis"
      icon="activity"
      isExpanded={isExpanded}
      onToggle={() => setIsExpanded(!isExpanded)}
      status={isForge ? 'CVForge Detected' : 'External PDF'}
    >
      <div className="space-y-4">
        <DiagnosticRow label="File" value={document.fileName} />
        <DiagnosticRow label="Pages" value={extraction ? String(extraction.pageCount) : 'Unavailable'} />
        <DiagnosticRow label="Characters" value={extraction ? String(extraction.text.length) : '0'} />
        <DiagnosticRow label="Extraction Confidence" value={extraction ? `${reliability}%` : '0%'} />
        
        <div className="pt-2">
          {isForge && (
            <p className="text-[10px] text-ink-3 italic leading-relaxed">
              This PDF was generated by CVForge. If it includes the embedded session attachment, restore uses that structured data instead of a best-effort external parse.
            </p>
          )}
          {!isForge && extraction && (
            <p className="text-[10px] text-ink-3 italic leading-relaxed">
              Extraction confidence describes readable text and draft confidence. It is separate from CV quality.
            </p>
          )}
        </div>

        {document.error && (
          <p className="text-xs text-red-200 font-medium" role="alert">
            {document.error}
          </p>
        )}
        {extraction && !hasSelectableText && (
          <p className="text-xs text-amber-200 font-medium" role="alert">
            No selectable text was found. This PDF may be scanned, image-only, or protected.
            Export a text-based PDF and try again; CVForge does not send the file to a cloud OCR service.
          </p>
        )}
        {extraction?.warnings.map((warning) => (
          <p
            key={warning}
            className="text-xs text-amber-200 font-medium"
            hidden={!hasSelectableText && warning === 'No selectable text was found in this PDF.'}
          >
            {warning}
          </p>
        ))}
      </div>
    </WorkbenchSectionCard>
  )
}

function EmptyDiagnostics() {
  const [isExpanded, setIsExpanded] = useState(true)
  return (
    <WorkbenchSectionCard
      title="Extraction Analysis"
      icon="activity"
      isExpanded={isExpanded}
      onToggle={() => setIsExpanded(!isExpanded)}
      status="Waiting"
    >
      <p className="text-xs text-ink-3 leading-relaxed">
        Upload a PDF to inspect page count and extracted text.
      </p>
    </WorkbenchSectionCard>
  )
}

function DiagnosticRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-16 text-xs">
      <span className="text-ink-4">{label}</span>
      <span className="text-ink text-right truncate">{value}</span>
    </div>
  )
}
