import {
  Anvil,
  Flame,
  Search,
  Plus,
  X,
  Check,
  ChevronRight,
  ChevronDown,
  Moon,
  Sun,
  Lock,
  Monitor,
  Users,
  FileDown,
  FileUp,
  Link,
  Circle,
  CheckCircle2,
  ArrowRight,
  Sparkles,
  Shield,
  FoldVertical,
  Activity,
  Eye,
  EyeOff,
  ArrowUp,
  ArrowDown,
  Upload,
  Download,
  FileText,
  Settings,
  Trash2,
  GripVertical,
  List,
  AlignLeft,
  type LucideIcon,
} from 'lucide-react'
import { type IconName } from './iconTypes'

type LucideIconName = Exclude<IconName, 'github'>

export const fallbackIcon = Search

export const iconMap: Record<LucideIconName, LucideIcon> = {
  anvil: Anvil,
  flame: Flame,
  search: Search,
  plus: Plus,
  x: X,
  check: Check,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  moon: Moon,
  sun: Sun,
  lock: Lock,
  device: Monitor,
  users: Users,
  import: FileDown,
  export: FileUp,
  link: Link,
  circle: Circle,
  'circle-check': CheckCircle2,
  'arrow-right': ArrowRight,
  spark: Sparkles,
  shield: Shield,
  fold: FoldVertical,
  activity: Activity,
  eye: Eye,
  'eye-off': EyeOff,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  upload: Upload,
  download: Download,
  'file-text': FileText,
  settings: Settings,
  trash: Trash2,
  grip: GripVertical,
  list: List,
  'align-left': AlignLeft,
}
